
ARG NODE_VERSION=20.3.0

FROM node:${NODE_VERSION}-alpine as base

WORKDIR /usr/src/app

COPY client/package.json ./client/

RUN npm install --silent --prefix ./client

COPY client ./client

EXPOSE 3000

CMD ["npm","start"]