# Use an official Node runtime as base image
FROM node:14

# Set the working directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the current directory contents into the container
COPY . .

# Make port 3001 available to the world outside this container
EXPOSE 3001

# Run server.js when the container launches
CMD ["npm", "start"]